### ISSUE TITLE
Support PHP 7.4

### ISSUE THREAD

**Issue by glassdimly** [boltdesignsystem/bolt#1630]
With PHP 7.4 installed, after running: `yarn install; yarn build` on `develop` build fails with the below output.

After downgrading/switching PHP versions with `brew install php@7.3; brew install brew-php-switcher; brew-php-switcher 7.3` it compiles and runs great.

```
﻿﻿﻿﻿﻿﻿﻿✖ The initial Pattern Lab Data compile failed!
Error:
          Error with code 255 after running: php:
        configuring pattern lab...
_data/ doesn't exist so you won't have dynamic data...

Fatal error: Uncaught ErrorException: Array and string offset access syntax with curly braces is deprecated in /Users/jeremy/www/bolt/docs-site/vendor/michelf/php-markdown/Michelf/MarkdownExtra.php:215
Stack trace:
#0 /Users/jeremy/www/bolt/docs-site/vendor/composer/ClassLoader.php(444): exceptions_error_handler(8192, 'Array and strin...', '/Users/jeremy/w...', 215, Array)
#1 /Users/jeremy/www/bolt/docs-site/vendor/composer/ClassLoader.php(444): include()
#2 /Users/jeremy/www/bolt/docs-site/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/Users/jeremy/w...')
#3 [internal function]: Composer\Autoload\ClassLoader->loadClass('Michelf\\Markdow...')
#4 /Users/jeremy/www/bolt/docs-site/vendor/pattern-lab/core/src/PatternLab/Parsers/Documentation.php(31): spl_autoload_call('Michelf\\Markdow...')
#5 /Users/jeremy/www/bolt/docs-site/vendor/pattern-lab/core/src/PatternLab/Parsers/Documentation.php(123): PatternLab\Parsers\Documentation::convertMarkdown('')
#6 /Users/jeremy/www/bolt/docs-site/vendor/pattern-lab/ in /Users/jeremy/www/bolt/docs-site/vendor/michelf/php-markdown/Michelf/MarkdownExtra.php on line 215
PHP Fatal error:  Uncaught ErrorException: Array and string offset access syntax with curly braces is deprecated in /Users/jeremy/www/bolt/docs-site/vendor/michelf/php-markdown/Michelf/MarkdownExtra.php:215
Stack trace:
#0 /Users/jeremy/www/bolt/docs-site/vendor/composer/ClassLoader.php(444): exceptions_error_handler(8192, 'Array and strin...', '/Users/jeremy/w...', 215, Array)
#1 /Users/jeremy/www/bolt/docs-site/vendor/composer/ClassLoader.php(444): include()
#2 /Users/jeremy/www/bolt/docs-site/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/Users/jeremy/w...')
#3 [internal function]: Composer\Autoload\ClassLoader->loadClass('Michelf\\Markdow...')
#4 /Users/jeremy/www/bolt/docs-site/vendor/pattern-lab/core/src/PatternLab/Parsers/Documentation.php(31): spl_autoload_call('Michelf\\Markdow...')
#5 /Users/jeremy/www/bolt/docs-site/vendor/pattern-lab/core/src/PatternLab/Parsers/Documentation.php(123): PatternLab\Parsers\Documentation::convertMarkdown('')
#6 /Users/jeremy/www/bolt/docs-site/vendor/pattern-lab/ in /Users/jeremy/www/bolt/docs-site/vendor/michelf/php-markdown/Michelf/MarkdownExtra.php on line 215

    at ChildProcess.<anonymous> (/Users/jeremy/www/bolt/packages/build-tools/utils/sh.js:60:18)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:210:5)
    at Pipe.<anonymous> (net.js:659:12)
(node:81632) UnhandledPromiseRejectionWarning: Error:
          Error with code 255 after running: php:
        configuring pattern lab...
_data/ doesn't exist so you won't have dynamic data...

Fatal error: Uncaught ErrorException: Array and string offset access syntax with curly braces is deprecated in /Users/jeremy/www/bolt/docs-site/vendor/michelf/php-markdown/Michelf/MarkdownExtra.php:215
Stack trace:
#0 /Users/jeremy/www/bolt/docs-site/vendor/composer/ClassLoader.php(444): exceptions_error_handler(8192, 'Array and strin...', '/Users/jeremy/w...', 215, Array)
#1 /Users/jeremy/www/bolt/docs-site/vendor/composer/ClassLoader.php(444): include()
#2 /Users/jeremy/www/bolt/docs-site/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/Users/jeremy/w...')
#3 [internal function]: Composer\Autoload\ClassLoader->loadClass('Michelf\\Markdow...')
#4 /Users/jeremy/www/bolt/docs-site/vendor/pattern-lab/core/src/PatternLab/Parsers/Documentation.php(31): spl_autoload_call('Michelf\\Markdow...')
#5 /Users/jeremy/www/bolt/docs-site/vendor/pattern-lab/core/src/PatternLab/Parsers/Documentation.php(123): PatternLab\Parsers\Documentation::convertMarkdown('')
#6 /Users/jeremy/www/bolt/docs-site/vendor/pattern-lab/ in /Users/jeremy/www/bolt/docs-site/vendor/michelf/php-markdown/Michelf/MarkdownExtra.php on line 215
PHP Fatal error:  Uncaught ErrorException: Array and string offset access syntax with curly braces is deprecated in /Users/jeremy/www/bolt/docs-site/vendor/michelf/php-markdown/Michelf/MarkdownExtra.php:215
Stack trace:
#0 /Users/jeremy/www/bolt/docs-site/vendor/composer/ClassLoader.php(444): exceptions_error_handler(8192, 'Array and strin...', '/Users/jeremy/w...', 215, Array)
#1 /Users/jeremy/www/bolt/docs-site/vendor/composer/ClassLoader.php(444): include()
#2 /Users/jeremy/www/bolt/docs-site/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/Users/jeremy/w...')
#3 [internal function]: Composer\Autoload\ClassLoader->loadClass('Michelf\\Markdow...')
#4 /Users/jeremy/www/bolt/docs-site/vendor/pattern-lab/core/src/PatternLab/Parsers/Documentation.php(31): spl_autoload_call('Michelf\\Markdow...')
#5 /Users/jeremy/www/bolt/docs-site/vendor/pattern-lab/core/src/PatternLab/Parsers/Documentation.php(123): PatternLab\Parsers\Documentation::convertMarkdown('')
#6 /Users/jeremy/www/bolt/docs-site/vendor/pattern-lab/ in /Users/jeremy/www/bolt/docs-site/vendor/michelf/php-markdown/Michelf/MarkdownExtra.php on line 215

    at ChildProcess.<anonymous> (/Users/jeremy/www/bolt/packages/build-tools/utils/sh.js:60:18)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:210:5)
    at Pipe.<anonymous> (net.js:659:12)
(node:81632) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:81632) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
⠋ Compiling Static Site...PHP Deprecated:  Unparenthesized `a ? b : c ? d : e` is deprecated. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)` in /Users/jeremy/www/bolt/docs-site/vendor/twig/twig/lib/Twig/Node.php on line 42
PHP Deprecated:  Unparenthesized `a ? b : c ? d : e` is deprecated. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)` in /Users/jeremy/www/bolt/docs-site/vendor/twig/twig/lib/Twig/Node.php on line 198
PHP Deprecated:  array_key_exists(): Using array_key_exists() on objects is deprecated. Use isset() or property_exists() instead in /Users/jeremy/www/bolt/docs-site/vendor/twig/twig/lib/Twig/Template.php on line 578
PHP Deprecated:  array_key_exists(): Using array_key_exists() on objects is deprecated. Use isset() or property_exists() instead in /Users/jeremy/www/bolt/docs-site/vendor/twig/twig/lib/Twig/Template.php on line 578
PHP Deprecated:  array_key_exists(): Using array_key_exists() on objects is deprecated. Use isset() or property_exists() instead in /Users/jeremy/www/bolt/docs-site/vendor/twig/twig/lib/Twig/Template.php on line 578

Deprecated: Unparenthesized `a ? b : c ? d : e` is deprecated. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)` in /Users/jeremy/www/bolt/docs-site/vendor/twig/twig/lib/Twig/Node.php on line 42

Deprecated: Unparenthesized `a ? b : c ? d : e` is deprecated. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)` in /Users/jeremy/www/bolt/docs-site/vendor/twig/twig/lib/Twig/Node.php on line 198
⠙ Compiling Static Site...PHP Deprecated:  array_key_exists(): Using array_key_exists() on objects is deprecated. Use isset() or property_exists() instead in /Users/jeremy/www/bolt/docs-site/vendor/twig/twig/lib/Twig/Template.php on line 578
PHP Deprecated:  array_key_exists(): Using array_key_exists() on objects is deprecated. Use isset() or property_exists() instead in /Users/jeremy/www/bolt/docs-site/vendor/twig/twig/lib/Twig/Template.php on line 578
PHP Deprecated:  array_key_exists(): Using array_key_exists() on objects is deprecated. Use isset() or property_exists() instead in /Users/jeremy/www/bolt/docs-site/vendor/twig/twig/lib/Twig/Template.php on line 578
PHP Deprecated:  array_key_exists(): Using array_key_exists() on objects is deprecated. Use isset() or property_exists() instead in /Users/jeremy/www/bolt/docs-site/vendor/twig/twig/lib/Twig/Template.php on line 578
...

﻿```

**Comment by margoromo** [comment]
Thanks @glassdimly!
