### ISSUE TITLE
Support node 13

### ISSUE THREAD

**Issue by glassdimly** [boltdesignsystem/bolt#1631]
When on node 13, `yarn install` and `yarn build` fail with the below errors.
```
$ nvm use default
Now using node v13.3.0 (npm v6.13.1)
```
Downgrading to node 12 works fine after (`rm -Rf node_modules; nvm install 12; nvm use 12`).
```
error /Users/jeremy/www/bolt/node_modules/sharp: Command failed.
Exit code: 1
Command: (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
Arguments:
Directory: /Users/jeremy/www/bolt/node_modules/sharp
Output:
info sharp Using cached /Users/jeremy/.npm/_libvips/libvips-8.7.4-darwin-x64.tar.gz
prebuild-install WARN install No prebuilt binaries found (target=13.3.0 runtime=node arch=x64 libc= platform=darwin)
gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.3
gyp info using node@13.3.0 | darwin | x64
gyp info find Python using Python version 2.7.10 found at "/usr/bin/python"
gyp info spawn /usr/bin/python
gyp info spawn args [
gyp info spawn args   '/Users/jeremy/www/bolt/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/jeremy/www/bolt/node_modules/sharp/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/jeremy/www/bolt/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/jeremy/Library/Caches/node-gyp/13.3.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/jeremy/Library/Caches/node-gyp/13.3.0',
gyp info spawn args   '-Dnode_gyp_dir=/Users/jeremy/www/bolt/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/jeremy/Library/Caches/node-gyp/13.3.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/jeremy/www/bolt/node_modules/sharp',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  TOUCH Release/obj.target/libvips-cpp.stamp
  CXX(target) Release/obj.target/sharp/src/common.o
  CXX(target) Release/obj.target/sharp/src/metadata.o
  CXX(target) Release/obj.target/sharp/src/stats.o
../src/stats.cc:130:19: error: no matching member function for call to 'Set'
        channels->Set(i, channelStat);
        ~~~~~~~~~~^~~
/Users/jeremy/Library/Caches/node-gyp/13.3.0/include/node/v8.h:3547:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/jeremy/Library/Caches/node-gyp/13.3.0/include/node/v8.h:3550:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
1 error generated.
make: *** [Release/obj.target/sharp/src/stats.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/jeremy/www/bolt/node_modules/node-gyp/lib/build.js:196:23)
gyp ERR! stack     at ChildProcess.emit (events.js:219:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:274:12)
gyp ERR! System Darwin 18.6.0
gyp ERR! command "/usr/local/opt/nvm/versions/node/v13.3.0/bin/node" "/Users/jeremy/www/bolt/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /Users/jeremy/www/bolt/node_modules/sharp
```

**Comment by margoromo** [comment]
Thanks @glassdimly!

**Comment by remydenton** [comment]
For now, the recommended approach is to just use node 12 (specifically, run `nvm use` in the project root to get whatever version Bolt best supports at any given time).  We should still fix this though, thanks for the bug report.

**Comment by remydenton** [comment]
Update to my previous comment, we'll only typically support LTS releases of node.  Supporting a version any sooner means we could run into bugs from dependencies (which is the case here) and only makes sense if there's some must-have feature in the newer version that's worth the potential instability.
